Lra 447 art survey display documents and images on the art item show page
lsa-mis/art_survey pull request #16
Opened 2022-11-07 16:53 UTC by britaumich

I took the procedure to add and display documents from our VOD application.
(I added indigo colors to tailwind because they are used in VOD)

Images are displayed with the lightbox from this article:
[Building a Lightbox with Hotwire and Swiper.js](https://blog.minthesize.com/lightbox-hotwire-swiper)

2022-11-07 23:06 UTC, rsmoke requested changes
Uncomment the variant manager for the thumbnails in application.rb and set the thumbnail size to a fixed width to prevent stretching in the _show_images.html.rb. 
LRA-450 will improve on this too

2022-11-07 23:22 UTC, britaumich commented on config/application.rb
> +    # config.active_storage.variant_processor = :mini_magick
Rails 7 (or ruby 3, I don't understand that clearly) requires vips to process images. You can install vips ('brew install vips', for example) or uncomment line 28 to keep using mini_magick.

2022-11-07 23:33 UTC, rsmoke commented on config/application.rb
> +    # config.active_storage.variant_processor = :mini_magick
because we don't have brew on Digital Ocean, probably uncommenting is the best solution. Uncommenting worked on my local

2022-11-07 23:43 UTC, britaumich commented
The :thumb variant is defined in the model. They added some new features to process images in Rails 7 (see the article
https://www.bigbinary.com/blog/rails-7-adds-ability-to-use-predefined-variants). 
I added the lightbox following this article [Building a Lightbox with Hotwire and Swiper.js](https://blog.minthesize.com/lightbox-hotwire-swiper).

I tried to play with :thumb sizes, but unsuccessfully.

2022-11-07 23:50 UTC, britaumich commented on config/application.rb
> +    # config.active_storage.variant_processor = :mini_magick
done

2022-11-08 16:56 UTC, rsmoke approved these changes

2022-11-08 16:56 UTC, merged